### ISSUE TITLE
convert PDF guide to markdown

### ISSUE THREAD

**Issue by onlyjob** [OpenNebula/addon-lxcone#1]
Please convert PDF guide to plain text. It will be ideal to use _markdown_ format and include instructions to `README.md`.

It is also important to remove `LXC+OpenNebula_Guide.pdf` because it is a generated file without source(s) which makes it "non-free" (i.e. non-distributable) from Debian prospective.

PDF guide is hard to use because of code formatting and copy/paste issues...

**Comment by jmdelafe** [comment]
Solved. https://github.com/OpenNebula/addon-lxcone/blob/master/Guide.md
