### ISSUE TITLE
copyright statement(s)

### ISSUE THREAD

**Issue by onlyjob** [OpenNebula/addon-lxcone#2]
Please add copyright statement to `README.md` to document copyright attribution for all files, including those without copyright/license information in headers.

Probably it would be something like:

    2013-2015 OpenNebula Project (OpenNebula.org), C12G Labs

If some parts of your work derived from [addon-lxc](https://github.com/OpenNebula/addon-lxc) project (I've noticed that at least `lxcrc` file is borrowed from _addon-lxc_) then please include `Copyright 2013 databus.pro` as well.

If only `lxcrc` file originates from _addon-lxc_ then I believe its copyright attribution can be overridden (or dropped) because file `lxcrc` contains exactly one line of trivial code and therefore most likely not copyright-able.

Also it would be nice to correct copyright years in headers -- I see no evidence of work prior to 2013 so copyright years couldn't be from 2002 like it is stated in most files.

Thanks.

**Comment by jmdelafe** [comment]
That file was already removed, it wasn't supposed to be uploaded.
Bests

**Comment by onlyjob** [comment]
What file is already removed? README still have no copyright statement. This problem is _not_ fixed.

**Comment by sergiojvg** [comment]
Sorry, we missed that. Now it's fixed. Thanks

**Comment by onlyjob** [comment]
Thanks, it is better. However I doubt about years range as there is no evidence of work prior to 2013. Can you please also check copyright years in headers?
