### ISSUE TITLE
Duplicate the functionality from LXD in addon-lxcone

### ISSUE THREAD

**Issue by kk-klose** [OpenNebula/addon-lxcone#6]
Beside you have the opportunity to use different hypervisor were is the 
advantage from **addon-lxcone** over using **LXD** in OpenNebula?
Most would be much easier / faster to implement using the REST-API 
of LXD. https://github.com/lxc/lxd/blob/master/doc/rest-api.md

LXD is backported to trusty and works already perfect on Xenial Xerus.
http://packages.ubuntu.com/de/trusty-backports/admin/lxd

**Comment by jmdelafe** [comment]
Thanks for the feedback!

By the time we started to develop LXCoNe, LXD wasn't ready to be used :( and we decided to use LXC through liblxc like LXD does.

There's a plan to migrate this driver to LXD soon, to get the LXD advantages over LXC. We will appreciate any help :)

**Comment by bmullan** [comment]
Great question as I was just searching to find whether LXD would be implemented as it would seem to make both local/remote mgmt/orchestration of LXC containers via the LXD REST api simpler for OpenNebula.

**Comment by jmdelafe** [comment]
We're moving forward to a new [LXD addon](https://github.com/OpenNebula/addon-lxdone). Check it! :)
